rm -rf alice.jsonld
rm -rf privatekeys.jsonld
rm -rf signed-residence.jsonld
rm -rf bbs-signed-residence.jsonld
rm -rf derived-residence.jsonld
rm -rf ./generated
rm -rf ./generate-distributed
rm -rf generated.ttl
rm -rf generated-distributed.ttl
rm -rf generated-dereferenced.ttl
rm -rf generated-distributed-dereferenced.ttl
rm -rf generated-distributed-collected-dereferenced.ttl